# Generated by Django 4.1.6 on 2023-02-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_cart_products_remove_cart_quantidade_cartitem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantidade',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantidade'),
        ),
    ]
