# Generated by Django 4.1.6 on 2023-02-12 23:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0006_alter_cart_cart_itens'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, choices=[(0, 'Pedido Efetuado'), (1, 'Pedido Enviado'), (2, 'Pedido Cancelado'), (3, 'Pedido Finalizado')], default=0, verbose_name='Situação')),
                ('cart_itens', models.ManyToManyField(blank=True, to='cart.cartitem', verbose_name='CartItems')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedido', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedido',
            },
        ),
    ]
